### ISSUE TITLE
 library "libflutter.so" not found

### ISSUE THREAD

**Issue by ishakdas** [Uuttssaavv/flutter-clean-architecture-riverpod#16]
Hello,
Unfortunately, I am getting the following error while trying to get the application up and running.

`Flutter initialization failed.
E/FlutterLoader( 6403): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader( 6403):         at java.util.concurrent.FutureTask.report(FutureTask.java:122)
E/FlutterLoader( 6403):         at java.util.concurrent.FutureTask.get(FutureTask.java:191)
E/FlutterLoader( 6403):         at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:241)
E/FlutterLoader( 6403):         at io.flutter.embedding.engine.FlutterEngineGroup.<init>(FlutterEngineGroup.java:63)
E/FlutterLoader( 6403):         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:324)
E/FlutterLoader( 6403):         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:189)
E/FlutterLoader( 6403):         at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:643)
E/FlutterLoader( 6403):         at android.app.Activity.performCreate(Activity.java:8305)
E/FlutterLoader( 6403):         at android.app.Activity.performCreate(Activity.java:8284)
E/FlutterLoader( 6403):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
E/FlutterLoader( 6403):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
E/FlutterLoader( 6403):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
E/FlutterLoader( 6403):         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/FlutterLoader( 6403):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/FlutterLoader( 6403):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/FlutterLoader( 6403):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/FlutterLoader( 6403):         at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader( 6403):         at android.os.Looper.loopOnce(Looper.java:201)
E/FlutterLoader( 6403):         at android.os.Looper.loop(Looper.java:288)
E/FlutterLoader( 6403):         at android.app.ActivityThread.main(ActivityThread.java:7872)
E/FlutterLoader( 6403):         at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader( 6403):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/FlutterLoader( 6403):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/FlutterLoader( 6403): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader( 6403):         at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/FlutterLoader( 6403):         at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/FlutterLoader( 6403):         at java.lang.System.loadLibrary(System.java:1661)
E/FlutterLoader( 6403):         at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/FlutterLoader( 6403):         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:191)
E/FlutterLoader( 6403):         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:184)
E/FlutterLoader( 6403):         at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/FlutterLoader( 6403):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/FlutterLoader( 6403):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/FlutterLoader( 6403):         at java.lang.Thread.run(Thread.java:1012)`

flutter doctor -v : 
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-TR)
    • Flutter version 3.13.9 on channel stable at /Users/user/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

flutter --version
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (3 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0

**Comment by Uuttssaavv** [comment]
You can try this : https://stackoverflow.com/a/73556352 
and update me if this works

**Comment by Uuttssaavv** [comment]
I am closing this assuming that it is solved :)
